import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/' as={'Home'}><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
          <Link href='/blog'><li>Blogs</li></Link>
        </ul>
      </nav>


      <main className={styles.main}>

      <h1 className={styles.title}>Welcome To Hunting Coder</h1>
      <p className={styles.description}>This is Blog for coders</p>

        <h2>Popular Content</h2>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>javascript is a programming language</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>javascript is a programming language</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>javascript is a programming language</p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
