import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>{`
        h2{
          font-size: 30px;
          font-family: 'Roboto Slab', serif;
        }
        
        h3{
          font-size: 22px;
        }
      `}</style>

      <Head>
        <title>Code The Web  |  Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      



      <main className={styles.main}>

      <h1 className={styles.title}>Welcome To <span>Code The Web</span></h1>

      <img className={styles.myimg} src="/home.jpg" height={427} width={1920} />

      <p className={styles.description}>This is a Blog for coders</p>

      <div>
      <h2>Popular Content</h2>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>javascript is a programming language</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>javascript is a programming language</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>javascript is a programming language</p>
          </div>
        </div>

      </div>
      
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
